### ISSUE TITLE
Translation to Portuguese of Brazil and adequacy Brazilian law

### ISSUE THREAD

**Issue by fabriciofs** [medbounaga/deftERP#4]
After translating the ERP for Portuguese , I will start to prepare it for Brazilian taxes in order to deal with the issuance of NF-e 's and import XML 's on supplier invoices

**Comment by fabriciofs** [comment]
After translating the ERP for Portuguese , I will start to prepare it for Brazilian taxes in order to deal with the issuance of NF-e 's and import XML 's on supplier invoices

**Comment by medbounaga** [comment]
@fabriciofs Great! Thank you for the contribution!

**Comment by mattmaciel** [comment]
@fabriciofs Are you still Working in this issue ?
