### ISSUE TITLE
Translation to Spanish

### ISSUE THREAD

**Issue by ajuliang** [medbounaga/deftERP#7]
Hello , I could work on the translation to Spanish.
I'm from Colombia. Greetings...

**Comment by mcrose** [comment]
@juligon yo comencé la traducción unos días atrás, será que podes darle una revisión ?
o qué tanto ya avanzaste, así no doblamos la tarea =)

**Comment by ajuliang** [comment]
Hola @mcrose . 
vale, No he iniciado con la tarea, ya que precisamente queria saber si alguien estaba en eso.
Podriamos crear una rama, sube sus cambios y nos podriamos distribuir e trabajo por módulos o algo similar. 
¿ Qué opina ?

**Comment by mcrose** [comment]
excelente
la ultima vez me quedé en la línea 231
solo que para asegurar no pisar ningun trabajo, nombré al archivo `Messages_es_PY.properties`

**Comment by ajuliang** [comment]
Vale, entonces si quiere creamos una rama llamada "spanish" y sube sus cambios. de esta manera, avanzamos ambos al mismo tiempo.
Si quiere contactemonos en skype para mayor conversación. Ya le envie una invitiación.

**Comment by mcrose** [comment]
me parece bien, puedo dejar eso a tu cargo, ahora tengo que seguir con la vida familiar :)

**Comment by ajuliang** [comment]
Ok, subiré la rama con los respectivos archivos y comienzo desde la linea 233: (CustomerRequired)

**Comment by medbounaga** [comment]
I don't understand Spanish so had to translate to understand what you guys are discussing :+1:  
I have added @juligon as a collaborator! Thank you guys for your contribution.
